# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rustyfilters, .registration = TRUE
NULL

#' Focal statistic over a stack of column-major layers.
#' @noRd
#' @keywords internal
rf_focal_rs <- function(x, nr, nc, nl, wr, wc, stat, edge, edge_value, na_omit) .Call(wrap__rf_focal_rs, x, nr, nc, nl, wr, wc, stat, edge, edge_value, na_omit)

#' @noRd
#' @keywords internal
rf_set_threads_rs <- function(n) .Call(wrap__rf_set_threads_rs, n)

#' @noRd
#' @keywords internal
rf_get_threads_rs <- function() .Call(wrap__rf_get_threads_rs)

# nolint end
