# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rustyfilters, .registration = TRUE
NULL

#' @noRd
#' @keywords internal
rf_set_threads_rs <- function(n) .Call(wrap__rf_set_threads_rs, n)

#' @noRd
#' @keywords internal
rf_get_threads_rs <- function() .Call(wrap__rf_get_threads_rs)

# nolint end
